branch-defaults:
  default:
    environment: null
global:
  application_name: study-sync
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: non-prod
  repository: null
  sc: null
  workspace_type: Application
